import os
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from src.config import SCOPES, SPREADSHEET_ID, RANGE_NAME

def get_sheets_service():
    """Authenticates and returns the Sheets service."""
    creds = None
    # We reuse the same token.json generated by Gmail login
    if os.path.exists('credentials/token.json'):
        creds = Credentials.from_authorized_user_file('credentials/token.json', SCOPES)
    return build('sheets', 'v4', credentials=creds)

def append_to_sheet(service, values):
    """Appends rows to the Google Sheet."""
    if not values: return

    body = {'values': values}
    
    # This appends data to the next available row
    service.spreadsheets().values().append(
        spreadsheetId=SPREADSHEET_ID,
        range=RANGE_NAME,
        valueInputOption="USER_ENTERED",
        body=body
    ).execute()